[features]
seeds = false
[programs.localnet]
crowdfunding = "EU42o87dBVzyMvAMx2VvBNbBZH5Syt5baRs6QybFomSq"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "/home/luismata/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
